# Sarracenia Docker Compose File
# For usage instructions, see the main project README.
services:
  sarracenia:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.${BUILD_TYPE:-native}
    container_name: sarracenia
    restart: unless-stopped
    ports:
      - "7277:7277"
      - "7278:7278"
    volumes:
      - sarracenia-data:/app
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:7278 || exit 1
      interval: 5m
      timeout: 3s
      retries: 3
      start_period: 2m


volumes:
  sarracenia-data:
    driver: local